swagger: "2.0"
info:
  description: "This is a server for the KPI schedule. \nYou can find out more about project at [GitHub](https://github.com/naz-olegovich/rozklad-kpi-remake-server)"
  version: "1.0.0"
  title: "ROAZKLAD KPI API"
  # termsOfService: "http://swagger.io/terms/"
  contact:
    email: "nazar.chopyk@gmail.com"
    # license:
    # name: "Apache 2.0"
    # url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
# basePath: "/v2"
tags:
  - name: "Groups"
    description: "Schedule for groups"
    # externalDocs:
    #   description: "Find out more"
    #   url: "http://swagger.io"
  - name: "Teachers"
    description: "Schedule for teachers"
# schemes:
# - "https"
# - "http"

paths:
  /api/groups:
    get:
      tags:
        - "Groups"
      summary: "Get a list of all the groups"
      description: "Returns a list of groups"
      operationId: "getGroups"
      consumes:
        - "application/json"

      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "limit"
          description: "Limits the number of groups to be returned"
          required: false
          type: integer
          default: 500

        - in: "query"
          name: "offset"
          description: "Offsets list of groups"
          required: false
          type: integer
          default: 0
      responses:
        "200":
          description: "successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GroupLists"
        "404":
          description: "Groups not found or db is empty"
          schema:
            items:
              $ref: "#/definitions/GroupListsError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"

  /api/groups/{groupId}/timetable:
    get:
      tags:
        - "Groups"
      summary: "Get schedule for group by id"
      description: "Returns the schedule of a specific group in a hierarchical form"
      operationId: "getGroupTimetableById"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of necessary group"
          required: true
          type: "integer"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GroupTimetable"
        "404":
          description: "Group not found"
          schema:
            items:
              $ref: "#/definitions/GroupError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"

  /api/groups/{groupName}/timetable:
    get:
      tags:
        - "Groups"
      summary: "Get schedule for group by name"
      description: "Returns the schedule of a specific group in a hierarchical form"
      operationId: "getGroupTimetableByName"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "groupName"
          in: "path"
          description: "ID of necessary group"
          required: true
          type: "string"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GroupTimetable"
        "404":
          description: "Group not found"
          schema:
            items:
              $ref: "#/definitions/GroupError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"




  /api/teachers:
    get:
      tags:
        - "Teachers"
      summary: "Get a list of all the teachers"
      description: "Returns a list of teachers"
      operationId: "getTeachersList"

      parameters:
        - in: "query"
          name: "limit"
          description: "Limits the number of teachers to be returned"
          required: false
          type: integer
          default: 500

        - in: "query"
          name: "offset"
          description: "Offsets list of teachers"
          required: false
          type: integer
          default: 0
      responses:
        "200":
          description: "successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TeacherLists"
        "404":
          description: "Teachers not found or db is empty"
          schema:
            items:
              $ref: "#/definitions/TeacherListsError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"



  /api/teachers/{teacherId}/lessons:
    get:
      tags:
        - "Teachers"
      summary: "Get lessons for teacher by id"
      description: "Returns a list of subjects for a necessary teacher"
      operationId: "getTeacherLessonsById"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "teacherId"
          in: "path"
          description: "ID of necessary teacher"
          required: true
          type: "integer"

      responses:
        "200":
          description: "successful response"
          schema:
            $ref: "#/definitions/TeacherLessons"
        "404":
          description: "Teacher not found"
          schema:
            items:
              $ref: "#/definitions/TeacherError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"

  /api/teachers/{teacherName}/lessons:
    get:
      tags:
        - "Teachers"
      summary: "Get lessons for teacher by name"
      description: "Returns a list of subjects for a necessary teacher"
      operationId: "getTeacherLessonsByName"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "teacherName"
          in: "path"
          description: "Name of necessary teacher"
          required: true
          type: "string"

      responses:
        "200":
          description: "successful response"
          schema:
            $ref: "#/definitions/TeacherLessons"
        "404":
          description: "Teacher not found"
          schema:
            items:
              $ref: "#/definitions/TeacherError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"

  /api/teachers/{teacherName}/timetable:
    get:
      tags:
        - "Teachers"
      summary: "Get timetable for teacher by name"
      description: "Returns the schedule for a necessary teacher in a hierarchical form"
      operationId: "getTeacherTimetableByName"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "teacherName"
          in: "path"
          description: "Name of necessary teacher"
          required: true
          type: "string"

      responses:
        "200":
          description: "successful response"
          schema:
            $ref: "#/definitions/TeacherTimatable"
        "404":
          description: "Teacher not found"
          schema:
            items:
              $ref: "#/definitions/TeacherError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"

  /api/teachers/{teacherId}/timetable:
    get:
      tags:
        - "Teachers"
      summary: "Get timetable for teacher by id"
      description: "Returns the schedule for a necessary teacher in a hierarchical form"
      operationId: "getTeacherTimetableById"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "teacherId"
          in: "path"
          description: "Id of necessary teacher"
          required: true
          type: "integer"

      responses:
        "200":
          description: "successful response"
          schema:
            $ref: "#/definitions/TeacherTimatable"
        "404":
          description: "Teacher not found"
          schema:
            items:
              $ref: "#/definitions/TeacherError"
        "500":
          description: "Server error occurred"
          schema:
            items:
              $ref: "#/definitions/ServerError"





# securityDefinitions:
#   petstore_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write:pets: "modify pets in your account"
#       read:pets: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"
definitions:
  GroupLists:
    type: "object"
    properties:
      id:
        type: "integer"

      name:
        type: "string"

      prefix:
        type: "string"

      okr:
        type: "string"

      type:
        type: "string"




  GroupTimetable:
    type: "object"
    properties:
      id:
        type: "integer"

      name:
        type: "string"

      prefix:
        type: "string"

      okr:
        type: "string"

      type:
        type: "string"

      weeks:
        type: "object"
        properties:
          week_number:
            type: "integer"

          days:
            type: "object"
            properties:

              "1":
                type: "object"
                properties:
                  day_name:
                    type: "string"

                  day_number:
                    type: "integer"

                  lessons:
                    type: "object"
                    properties:
                      lesson_id:
                        type: "integer"

                      group_id:
                        type: "integer"

                      day_number:
                        type: "integer"

                      day_name:
                        type: "string"

                      lesson_name:
                        type: "string"

                      lesson_full_name:
                        type: "string"

                      lesson_number:
                        type: "integer"

                      lesson_room:
                        type: "integer"

                      lesson_type:
                        type: "string"

                      teacher_name:
                        type: "string"

                      lesson_week:
                        type: "integer"

                      time_start:
                        type: "string"

                      time_end:
                        type: "string"

                      rate:
                        type: "integer"


                      teachers:
                        type: "object"
                        properties:
                          teacher_id:
                            type: "integer"

                          teacher_name:
                            type: "string"

                          teacher_full_name:
                            type: "string"

                          teacher_short_name:
                            type: "string"

                          teacher_url:
                            type: "string"

                          teacher_rating:
                            type: "string"

                      rooms:
                        type: "object"
                        properties:
                          room_id:
                            type: "integer"

                          room_name:
                            type: "integer"

                          room_latitude:
                            type: "number"

                          room_longitude:
                            type: "number"



  TeacherLists:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"

      name:
        type: "string"

      fullName:
        type: "string"

      shortName:
        type: "string"



  TeacherLessons:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"

      name:
        type: "string"

      fullName:
        type: "string"

      shortName:
        type: "string"

      lessons:
        type: "object"
        properties:
          lesson_id:
            type: "integer"
          day_number:
            type: "integer"
          day_name:
            type: "string"
          lesson_name:
            type: "string"
          lesson_full_name:
            type: "string"
          lesson_number:
            type: "integer"
          lesson_room:
            type: "string"
          lesson_type:
            type: "string"
          teacher_name:
            type: "string"
          lesson_week:
            type: "integer"
          time_start:
            type: "string"
          time_end:
            type: "string"
          rate:
            type: "number"
          teachers:
            type: "object"
          rooms:
            type: "object"
            properties:
              room_id:
                type: "integer"
              room_name:
                type: "string"
              room_latitude:
                type: "number"
              room_longitude:
                type: "number"


  TeacherTimatable:
    type: "object"
    properties:
      id:
        type: "integer"

      name:
        type: "string"

      fullName:
        type: "string"

      shortName:
        type: "string"

      weeks:
        type: "object"
        properties:
          week_number:
            type: "integer"

          days:
            type: "object"
            properties:

              "1":
                type: "object"
                properties:
                  day_name:
                    type: "string"

                  day_number:
                    type: "integer"

                  lessons:
                    type: "object"
                    properties:
                      lesson_id:
                        type: "integer"

                      group_id:
                        type: "integer"

                      day_number:
                        type: "integer"

                      day_name:
                        type: "string"

                      lesson_name:
                        type: "string"

                      lesson_full_name:
                        type: "string"

                      lesson_number:
                        type: "integer"

                      lesson_room:
                        type: "integer"

                      lesson_type:
                        type: "string"

                      teacher_name:
                        type: "string"

                      lesson_week:
                        type: "integer"

                      time_start:
                        type: "string"

                      time_end:
                        type: "string"

                      rate:
                        type: "integer"


                      teachers:
                        type: "object"
                        properties:
                          teacher_id:
                            type: "integer"

                          teacher_name:
                            type: "string"

                          teacher_full_name:
                            type: "string"

                          teacher_short_name:
                            type: "string"

                          teacher_url:
                            type: "string"

                          teacher_rating:
                            type: "string"

                      rooms:
                        type: "object"
                        properties:
                          room_id:
                            type: "integer"

                          room_name:
                            type: "integer"

                          room_latitude:
                            type: "number"

                          room_longitude:
                            type: "number"

  GroupListsError:
    type: "object"
    properties:
      statusCode:
        type: "integer"
        default: 404

      message:
        type: "string"
        default: "Groups not found or db is empty"

  GroupError:
    type: "object"
    properties:
      statusCode:
        type: "integer"
        default: 404

      message:
        type: "string"
        default: "Group not found"

  TeacherListsError:
    type: "object"
    properties:
      statusCode:
        type: "integer"
        default: 404

      message:
        type: "string"
        default: "Teacher not found or db is empty"

  TeacherError:
    type: "object"
    properties:
      statusCode:
        type: "integer"
        default: 404

      message:
        type: "string"
        default: "Teacher not found"

  ServerError:
    type: "object"
    properties:
      statusCode:
        type: "integer"
        default: 500

      message:
        type: "string"
        default: "Server error occurred"

# externalDocs:
#   description: "Find out more about Swagger"
#   url: "http://swagger.io"